// <auto-generated />
using System;
using CalorieTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260920091421_AddFaceAccessoryCosmetics")]
    partial class AddFaceAccessoryCosmetics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CalorieTracker.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Models.CapyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CapyItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Expression",
                            ImagePath = "/images/capy/expressions/Capy-Base.png",
                            IsActive = true,
                            IsDefault = true,
                            IsStarter = true,
                            Name = "Base Capy"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-Brown.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Brown T-Shirt"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-Charcoal.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Charcoal T-Shirt"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-ComfyCapy.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Comfy Capy T-Shirt"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-Cream.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Cream T-Shirt"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-Lavender.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Lavender T-Shirt"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-Lime.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Lime T-Shirt"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-Mustard.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Mustard T-Shirt"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-Navy.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Navy T-Shirt"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-Sage.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Sage T-Shirt"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-SkyBlue.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Sky Blue T-Shirt"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-White.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "White T-Shirt"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-ZZZ.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "ZZZ T-Shirt"
                        },
                        new
                        {
                            Id = 2,
                            Category = "HatHair",
                            ImagePath = "/images/capy/hats-hair/Capy-CowboyHat.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Cowboy Hat"
                        },
                        new
                        {
                            Id = 3,
                            Category = "HatHair",
                            ImagePath = "/images/capy/hats-hair/PartyHat-BlueYellow.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Blue & Yellow Party Hat"
                        },
                        new
                        {
                            Id = 4,
                            Category = "FaceAccessory",
                            ImagePath = "/images/capy/face-accessories/Sunglasses-Cool.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Cool Sunglasses"
                        },
                        new
                        {
                            Id = 27,
                            Category = "FaceAccessory",
                            ImagePath = "/images/capy/face-accessories/capy-bandaid.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Bandage"
                        },
                        new
                        {
                            Id = 28,
                            Category = "FaceAccessory",
                            ImagePath = "/images/capy/face-accessories/capy-duckbill.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Duck Bill"
                        },
                        new
                        {
                            Id = 29,
                            Category = "FaceAccessory",
                            ImagePath = "/images/capy/face-accessories/capy-eyepatch.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Eye Patch"
                        },
                        new
                        {
                            Id = 30,
                            Category = "FaceAccessory",
                            ImagePath = "/images/capy/face-accessories/capy-handlebar-mustache.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Handlebar Moustache"
                        },
                        new
                        {
                            Id = 31,
                            Category = "FaceAccessory",
                            ImagePath = "/images/capy/face-accessories/capy-heart-glasses.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Heart Glasses"
                        },
                        new
                        {
                            Id = 32,
                            Category = "FaceAccessory",
                            ImagePath = "/images/capy/face-accessories/capy-heart-sticker.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Heart Sticker"
                        },
                        new
                        {
                            Id = 33,
                            Category = "FaceAccessory",
                            ImagePath = "/images/capy/face-accessories/capy-hypnoglasses.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Hypno Glasses"
                        },
                        new
                        {
                            Id = 34,
                            Category = "FaceAccessory",
                            ImagePath = "/images/capy/face-accessories/capy-pixel-glasses.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Pixel Glasses"
                        },
                        new
                        {
                            Id = 5,
                            Category = "NeckAccessory",
                            ImagePath = "/images/capy/neck-accessories/Scarf-GreenRed.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Green & Red Scarf"
                        },
                        new
                        {
                            Id = 6,
                            Category = "NeckAccessory",
                            ImagePath = "/images/capy/neck-accessories/Tie-RedAndWhite.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Red & White Tie"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-Pink.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Pink T-Shirt"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-Banana.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Banana"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-Fields.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Fields"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-PalePink.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Pale Pink"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-PalePurple.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Pale Purple"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-Sky.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Sky"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-White.png",
                            IsActive = true,
                            IsDefault = true,
                            IsStarter = true,
                            Name = "White"
                        },
                        new
                        {
                            Id = 14,
                            Category = "HatHair",
                            ImagePath = "/images/capy/hats-hair/Capy-Crown-Gold.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = false,
                            Name = "Gold Crown"
                        });
                });

            modelBuilder.Entity("CalorieTracker.Models.CommunityFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CanonicalServingSize")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fat")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeratorNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortionLabel")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Protein")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServingBasis")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ServingSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServingUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceFoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmitterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("SourceFoodId")
                        .IsUnique()
                        .HasFilter("\"SourceFoodId\" IS NOT NULL");

                    b.HasIndex("SubmitterId");

                    b.HasIndex("Status", "Name", "Id");

                    b.ToTable("CommunityFoods", null, t =>
                        {
                            t.HasCheckConstraint("CK_CommunityFoods_Basis", "\"ServingBasis\" IN (0, 1)");

                            t.HasCheckConstraint("CK_CommunityFoods_Name", "length(trim(\"Name\")) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_CommunityFoods_Nutrition", "\"Calories\" >= 0 AND CAST(\"Protein\" AS REAL) >= 0 AND CAST(\"Carbohydrates\" AS REAL) >= 0 AND CAST(\"Fat\" AS REAL) >= 0 AND CAST(\"ServingSize\" AS REAL) > 0 AND CAST(\"CanonicalServingSize\" AS REAL) > 0");

                            t.HasCheckConstraint("CK_CommunityFoods_Review", "(\"Status\" = 0 AND \"ReviewedUtc\" IS NULL) OR (\"Status\" IN (1, 2) AND \"ReviewedUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CommunityFoods_Status", "\"Status\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("CalorieTracker.Models.CommunityFoodVote", b =>
                {
                    b.Property<int>("CommunityFoodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommunityFoodId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommunityFoodVotes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CommunityFoodVotes_Value", "\"Value\" IN (-1, 1)");
                        });
                });

            modelBuilder.Entity("CalorieTracker.Models.DailyMaintenanceSnapshot", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaintenanceCalories")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "Date");

                    b.ToTable("DailyMaintenanceSnapshots");
                });

            modelBuilder.Entity("CalorieTracker.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApproximationLabel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CaloriesSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CanonicalServingSizeSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarbohydratesSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FatSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoodPortionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproximate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PortionLabelSnapshot")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortionNameSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PortionQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProteinSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServingBasisSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ServingSizeSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServingUnitSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("FoodPortionId");

                    b.HasIndex("UserId", "FoodId");

                    b.HasIndex("UserId", "Date", "Id");

                    b.ToTable("DiaryEntries");
                });

            modelBuilder.Entity("CalorieTracker.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CanonicalServingSize")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fat")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PortionLabel")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Protein")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServingBasis")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ServingSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServingUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Source", "ExternalId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL AND \"Source\" IS NOT NULL AND \"ExternalId\" IS NOT NULL");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("CalorieTracker.Models.FoodPortion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodPortions");
                });

            modelBuilder.Entity("CalorieTracker.Models.SavedCapyOutfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BackgroundId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClothesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpressionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FaceAccessoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HatHairId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NeckAccessoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("SavedCapyOutfits");
                });

            modelBuilder.Entity("CalorieTracker.Models.SavedMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("SavedMeals");
                });

            modelBuilder.Entity("CalorieTracker.Models.SavedMealItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApproximationLabel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CaloriesSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CanonicalServingSizeSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarbohydratesSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FatSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoodPortionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproximate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortionLabelSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortionNameSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PortionQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProteinSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("SavedMealId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServingBasisSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ServingSizeSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServingUnitSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("FoodPortionId");

                    b.HasIndex("SavedMealId");

                    b.ToTable("SavedMealItems");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserAchievement", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AchievementKey")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UnlockedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "AchievementKey");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserCapyAppearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BackgroundId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClothesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpressionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FaceAccessoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HatHairId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NeckAccessoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("ClothesId");

                    b.HasIndex("ExpressionId");

                    b.HasIndex("FaceAccessoryId");

                    b.HasIndex("HatHairId");

                    b.HasIndex("NeckAccessoryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCapyAppearances");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserCapyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapyItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapyItemId");

                    b.HasIndex("UserId", "CapyItemId")
                        .IsUnique();

                    b.ToTable("UserCapyItems");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserDailyActivity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LocalDate");

                    b.ToTable("UserDailyActivities");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculationSex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CustomCalorieTarget")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GoalWeightKg")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeeklyGoalKg")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserProgressionState", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AchievementBackfillVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("UserId");

                    b.ToTable("UserProgressionStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserProgressionStates_BackfillVersion_NonNegative", "\"AchievementBackfillVersion\" >= 0");
                        });
                });

            modelBuilder.Entity("CalorieTracker.Models.UserXpEvent", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AwardedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "EventKey");

                    b.ToTable("UserXpEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserXpEvents_Amount_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-standard",
                            ConcurrencyStamp = "role-standard",
                            Name = "Standard",
                            NormalizedName = "STANDARD"
                        },
                        new
                        {
                            Id = "role-beta",
                            ConcurrencyStamp = "role-beta",
                            Name = "Beta",
                            NormalizedName = "BETA"
                        },
                        new
                        {
                            Id = "role-admin",
                            ConcurrencyStamp = "role-admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-owner",
                            ConcurrencyStamp = "role-owner",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Models.CommunityFood", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CalorieTracker.Models.Food", null)
                        .WithMany()
                        .HasForeignKey("SourceFoodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CalorieTracker.Models.CommunityFoodVote", b =>
                {
                    b.HasOne("CalorieTracker.Models.CommunityFood", "CommunityFood")
                        .WithMany("Votes")
                        .HasForeignKey("CommunityFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunityFood");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.DailyMaintenanceSnapshot", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.DiaryEntry", b =>
                {
                    b.HasOne("CalorieTracker.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Models.FoodPortion", "FoodPortion")
                        .WithMany()
                        .HasForeignKey("FoodPortionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("FoodPortion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.Food", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.FoodPortion", b =>
                {
                    b.HasOne("CalorieTracker.Models.Food", "Food")
                        .WithMany("Portions")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("CalorieTracker.Models.SavedCapyOutfit", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalorieTracker.Models.SavedMeal", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.SavedMealItem", b =>
                {
                    b.HasOne("CalorieTracker.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Models.FoodPortion", "FoodPortion")
                        .WithMany()
                        .HasForeignKey("FoodPortionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.SavedMeal", "SavedMeal")
                        .WithMany("Items")
                        .HasForeignKey("SavedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("FoodPortion");

                    b.Navigation("SavedMeal");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserAchievement", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalorieTracker.Models.UserCapyAppearance", b =>
                {
                    b.HasOne("CalorieTracker.Models.CapyItem", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.CapyItem", "Clothes")
                        .WithMany()
                        .HasForeignKey("ClothesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.CapyItem", "Expression")
                        .WithMany()
                        .HasForeignKey("ExpressionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.CapyItem", "FaceAccessory")
                        .WithMany()
                        .HasForeignKey("FaceAccessoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.CapyItem", "HatHair")
                        .WithMany()
                        .HasForeignKey("HatHairId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.CapyItem", "NeckAccessory")
                        .WithMany()
                        .HasForeignKey("NeckAccessoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Clothes");

                    b.Navigation("Expression");

                    b.Navigation("FaceAccessory");

                    b.Navigation("HatHair");

                    b.Navigation("NeckAccessory");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserCapyItem", b =>
                {
                    b.HasOne("CalorieTracker.Models.CapyItem", "CapyItem")
                        .WithMany()
                        .HasForeignKey("CapyItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapyItem");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserDailyActivity", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalorieTracker.Models.UserProfile", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("CalorieTracker.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserProgressionState", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalorieTracker.Models.UserXpEvent", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalorieTracker.Data.ApplicationUser", b =>
                {
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CalorieTracker.Models.CommunityFood", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("CalorieTracker.Models.Food", b =>
                {
                    b.Navigation("Portions");
                });

            modelBuilder.Entity("CalorieTracker.Models.SavedMeal", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
