// <auto-generated />
using System;
using CalorieTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260901181346_AddCapyStarterItems")]
    partial class AddCapyStarterItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CalorieTracker.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Models.CapyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CapyItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Expression",
                            ImagePath = "/images/capy/expressions/Capy-Base.png",
                            IsActive = true,
                            IsDefault = true,
                            IsStarter = true,
                            Name = "Base Capy"
                        },
                        new
                        {
                            Id = 2,
                            Category = "HatHair",
                            ImagePath = "/images/capy/hats-hair/Capy-CowboyHat.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Cowboy Hat"
                        },
                        new
                        {
                            Id = 3,
                            Category = "HatHair",
                            ImagePath = "/images/capy/hats-hair/PartyHat-BlueYellow.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Blue & Yellow Party Hat"
                        },
                        new
                        {
                            Id = 4,
                            Category = "FaceAccessory",
                            ImagePath = "/images/capy/face-accessories/Sunglasses-Cool.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Cool Sunglasses"
                        },
                        new
                        {
                            Id = 5,
                            Category = "NeckAccessory",
                            ImagePath = "/images/capy/neck-accessories/Scarf-GreenRed.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Green & Red Scarf"
                        },
                        new
                        {
                            Id = 6,
                            Category = "NeckAccessory",
                            ImagePath = "/images/capy/neck-accessories/Tie-RedAndWhite.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Red & White Tie"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Clothes",
                            ImagePath = "/images/capy/clothes/TShirt-Pink.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Pink T-Shirt"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-Banana.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Banana"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-Fields.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Fields"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-PalePink.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Pale Pink"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-PalePurple.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Pale Purple"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-Sky.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = true,
                            Name = "Sky"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Background",
                            ImagePath = "/images/capy/backgrounds/BG-White.png",
                            IsActive = true,
                            IsDefault = true,
                            IsStarter = true,
                            Name = "White"
                        },
                        new
                        {
                            Id = 14,
                            Category = "HatHair",
                            ImagePath = "/images/capy/hats-hair/Capy-Crown-Gold.png",
                            IsActive = true,
                            IsDefault = false,
                            IsStarter = false,
                            Name = "Gold Crown"
                        });
                });

            modelBuilder.Entity("CalorieTracker.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoodPortionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PortionQuantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("FoodPortionId");

                    b.HasIndex("UserId");

                    b.ToTable("DiaryEntries");
                });

            modelBuilder.Entity("CalorieTracker.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fat")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Protein")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ServingSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServingUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("CalorieTracker.Models.FoodPortion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodPortions");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserCapyAppearance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BackgroundId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClothesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpressionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FaceAccessoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HatHairId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NeckAccessoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("ClothesId");

                    b.HasIndex("ExpressionId");

                    b.HasIndex("FaceAccessoryId");

                    b.HasIndex("HatHairId");

                    b.HasIndex("NeckAccessoryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCapyAppearances");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserCapyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapyItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapyItemId");

                    b.HasIndex("UserId", "CapyItemId")
                        .IsUnique();

                    b.ToTable("UserCapyItems");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CalculationSex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CustomCalorieTarget")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GoalWeightKg")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("WeeklyGoalKg")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CalorieTracker.Models.DiaryEntry", b =>
                {
                    b.HasOne("CalorieTracker.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Models.FoodPortion", "FoodPortion")
                        .WithMany()
                        .HasForeignKey("FoodPortionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CalorieTracker.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("FoodPortion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.Food", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.FoodPortion", b =>
                {
                    b.HasOne("CalorieTracker.Models.Food", "Food")
                        .WithMany("Portions")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserCapyAppearance", b =>
                {
                    b.HasOne("CalorieTracker.Models.CapyItem", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.CapyItem", "Clothes")
                        .WithMany()
                        .HasForeignKey("ClothesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.CapyItem", "Expression")
                        .WithMany()
                        .HasForeignKey("ExpressionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.CapyItem", "FaceAccessory")
                        .WithMany()
                        .HasForeignKey("FaceAccessoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.CapyItem", "HatHair")
                        .WithMany()
                        .HasForeignKey("HatHairId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Models.CapyItem", "NeckAccessory")
                        .WithMany()
                        .HasForeignKey("NeckAccessoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Clothes");

                    b.Navigation("Expression");

                    b.Navigation("FaceAccessory");

                    b.Navigation("HatHair");

                    b.Navigation("NeckAccessory");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserCapyItem", b =>
                {
                    b.HasOne("CalorieTracker.Models.CapyItem", "CapyItem")
                        .WithMany()
                        .HasForeignKey("CapyItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapyItem");
                });

            modelBuilder.Entity("CalorieTracker.Models.UserProfile", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("CalorieTracker.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CalorieTracker.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalorieTracker.Data.ApplicationUser", b =>
                {
                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CalorieTracker.Models.Food", b =>
                {
                    b.Navigation("Portions");
                });
#pragma warning restore 612, 618
        }
    }
}
